{
  "query": "Quinn is a pure-Rust, async-compatible implementation of the IETF QUIC transport protocol. As of quinn-proto 0.11, it is possible for a server to `accept()`, `retry()`, `refuse()`, or `ignore()` an `Incoming` connection. However, calling `retry()` on an unvalidated connection exposes the server to a likely panic in the following situations 1. Calling `refuse` or `ignore` on the resulting validated connection, if a duplicate initial packet is received. This issue can go undetected until a servers `refuse()`/`ignore()` code path is exercised, such as to stop a denial of service attack. 2. Accepting when the initial packet for the resulting validated connection fails to decrypt or exhausts connection IDs, if a similar initial packet that successfully decrypts and doesnt exhaust connection IDs is received. This issue can go undetected if clients are well-behaved. The former situation was observed in a real application, while the latter is only theoretical.",
  "count": 11,
  "results": [
    {
      "cwe_id": "789",
      "name": "Memory Allocation with Excessive Size Value",
      "abstraction": "Variant",
      "score": 751.7905894076309,
      "original_score": 751.7905894076309,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "770",
      "name": "Allocation of Resources Without Limits or Throttling",
      "abstraction": "Base",
      "score": 749.5886566228648,
      "original_score": 749.5886566228648,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "1284",
      "name": "Improper Validation of Specified Quantity in Input",
      "abstraction": "Base",
      "score": 720.2595839414587,
      "original_score": 720.2595839414587,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "617",
      "name": "Reachable Assertion",
      "abstraction": "Base",
      "score": 713.5157157199233,
      "original_score": 713.5157157199233,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "295",
      "name": "Improper Certificate Validation",
      "abstraction": "Base",
      "score": 705.6125923778554,
      "original_score": 705.6125923778554,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "400",
      "name": "Uncontrolled Resource Consumption",
      "abstraction": "Class",
      "score": 704.635733209751,
      "original_score": 704.635733209751,
      "mapping_usage": "Discouraged"
    },
    {
      "cwe_id": "362",
      "name": "Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')",
      "abstraction": "Class",
      "score": 702.8110929930936,
      "original_score": 702.8110929930936,
      "mapping_usage": "Allowed-with-Review"
    },
    {
      "cwe_id": "835",
      "name": "Loop with Unreachable Exit Condition ('Infinite Loop')",
      "abstraction": "Base",
      "score": 693.5986105225749,
      "original_score": 693.5986105225749,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "346",
      "name": "Origin Validation Error",
      "abstraction": "Class",
      "score": 692.8580036253395,
      "original_score": 692.8580036253395,
      "mapping_usage": "Allowed-with-Review"
    },
    {
      "cwe_id": "1286",
      "name": "Improper Validation of Syntactic Correctness of Input",
      "abstraction": "Base",
      "score": 689.8094384589118,
      "original_score": 689.8094384589118,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "119",
      "name": "Improper Restriction of Operations within the Bounds of a Memory Buffer",
      "abstraction": "Class",
      "score": 237.00729008317597,
      "original_score": 237.00729008317597,
      "mapping_usage": "Discouraged"
    }
  ],
  "statistics": {
    "min": 237.00729008317597,
    "max": 751.7905894076309,
    "mean": 669.22611881478,
    "median": 704.635733209751,
    "count": 11
  }
}